library(data.table)

#set working directory
setwd('/Users/analutzky/Desktop/')


############################ GETTING STARTED ############################

# read French file of Parcoursup 2020
Table_parcoursup_2020=fread('/Users/analutzky/Desktop/fr-esr-parcoursup.csv')

# showing it excel-like
View(Table_parcoursup_2020)
# showing column names
colnames(Table_parcoursup_2020)
# put them into a variable
var.names=colnames(Table_parcoursup_2020)
### getting rid of space and special characters in columns names 
colnames(Table_parcoursup_2020)=make.names(var.names)
# showing column names
colnames(Table_parcoursup_2020)

Table_parcoursup_2020$Concours.communs.et.banques.d.épreuves
Table_parcoursup_2020$Établissement
Filieres=Table_parcoursup_2020$Filière.de.formation.très.agrégée
unique(Filieres)
# "Ecole d'Ingénieur" 
# "BTS"               
# "Ecole de Commerce" 
# "CPGE"              
# "DUT"               
# "Licence"          
# "Autre formation"   
# "Licence_Las"       
# "IFSI"              
# "EFTS"              
# "PASS" 


############################ PASS ############################

Table_PASS=Table_parcoursup_2020[Filière.de.formation.très.agrégée=="PASS",]
Effectifs_PASS=Table_PASS[, .(Filiere=Filière.de.formation.très.agrégée, Etab=Établissement, candidates=sum(Dont.effectif.des.candidates.pour.une.formation), candidats_PP=sum(Effectif.total.des.candidats.en.phase.principale), candidats_PC=sum(Effectif.total.des.candidats.en.phase.complémentaire), admis_PP=sum(Effectif.des.admis.en.phase.principale), admis_PC=sum(Effectif.des.admis.en.phase.complémentaire), admises=sum(Dont.effectif.des.candidates.admises), admis_neo_B=sum(Effectif.des.admis.néo.bacheliers), admis_neo_B_G=sum(Effectif.des.admis.néo.bacheliers.généraux), admis_neo_B_techno=sum(Effectif.des.admis.néo.bacheliers.technologiques), admis_neo_B_pro=sum(Effectif.des.admis.néo.bacheliers.professionnels), admis_neo_B_TB=sum(Dont.effectif.des.admis.néo.bacheliers.avec.mention.Très.Bien.au.bac)),by=Établissement]
# (capacite=sum(Capacité.de.l.établissement.par.formation), candidats=sum(Effectif.total.des.candidats.pour.une.formation)
# Error in list(sum(Capacité.de.l.établissement.par.formation), sum(Effectif.total.des.candidats.pour.une.formation),  : 
#   l'argument 12 est vide

Effectifs_PASS=Effectifs_PASS[, part_candidates:=candidates/(candidats_PC+candidats_PP)*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, part_admises:=admises/(admis_PP+admis_PC)*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, selectivite:=(admis_PP+admis_PC)/(candidats_PC+candidats_PP)*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, part_admis_neo_B:=admis_neo_B/(admis_PP+admis_PC)*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, part_admis_neo_B_G_parmi_neoB:=admis_neo_B_G/admis_neo_B*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, part_admis_neo_B_techno_parmi_neoB:=admis_neo_B_techno/admis_neo_B*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, part_admis_neo_B_pro_parmi_neoB:=admis_neo_B_pro/admis_neo_B*100,by=Établissement]
Effectifs_PASS=Effectifs_PASS[, part_admis_neo_B_TB_parmi_neoB:=admis_neo_B_TB/admis_neo_B*100,by=Établissement]

############################ LAS ############################

Table_LAS=Table_parcoursup_2020[Filière.de.formation.très.agrégée=="Licence_Las",]
Effectifs_LAS=Table_LAS[, .(Filiere=Filière.de.formation.très.agrégée, Etab=Établissement, candidates=sum(Dont.effectif.des.candidates.pour.une.formation), candidats_PP=sum(Effectif.total.des.candidats.en.phase.principale), candidats_PC=sum(Effectif.total.des.candidats.en.phase.complémentaire), admis_PP=sum(Effectif.des.admis.en.phase.principale), admis_PC=sum(Effectif.des.admis.en.phase.complémentaire), admises=sum(Dont.effectif.des.candidates.admises), admis_neo_B=sum(Effectif.des.admis.néo.bacheliers), admis_neo_B_G=sum(Effectif.des.admis.néo.bacheliers.généraux), admis_neo_B_techno=sum(Effectif.des.admis.néo.bacheliers.technologiques), admis_neo_B_pro=sum(Effectif.des.admis.néo.bacheliers.professionnels), admis_neo_B_TB=sum(Dont.effectif.des.admis.néo.bacheliers.avec.mention.Très.Bien.au.bac)),by=Filière.de.formation.détaillée]

Effectifs_LAS=Effectifs_LAS[, part_candidates:=candidates/(candidats_PC+candidats_PP)*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, part_admises:=admises/(admis_PP+admis_PC)*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, selectivite:=(admis_PP+admis_PC)/(candidats_PC+candidats_PP)*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, part_admis_neo_B:=admis_neo_B/(admis_PP+admis_PC)*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, part_admis_neo_B_G_parmi_neoB:=admis_neo_B_G/admis_neo_B*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, part_admis_neo_B_techno_parmi_neoB:=admis_neo_B_techno/admis_neo_B*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, part_admis_neo_B_pro_parmi_neoB:=admis_neo_B_pro/admis_neo_B*100,by=Filière.de.formation.détaillée]
Effectifs_LAS=Effectifs_LAS[, part_admis_neo_B_TB_parmi_neoB:=admis_neo_B_TB/admis_neo_B*100,by=Filière.de.formation.détaillée]

############################ PASS ET LAS ############################
Effectifs_LAS_et_PASS=rbind(Effectifs_PASS, Effectifs_LAS)

Table_ecoles_ingenieurs=Table_parcoursup_2020[Filière.de.formation.très.agrégée=="Ecole d'Ingénieur",]
Ecoles_inge=Table_ecoles_ingenieurs$Établissement   
unique(Ecoles_inge)
# [1] "La Prépa des INP - Groupe INP - Toulouse"                                                      
#   [2] "Polytech Orléans"                                                                              
#   [3] "Polytech Lille"                                                                                
#   [4] "Polytech Lille"                                                                                
#   [5] "Polytech Clermont-Ferrand"                                                                     
#   [6] "ENIB Brest"                                                                                    
#   [7] "ENIM Metz"                                                                                     
#   [8] "INSA Centre Val de Loire"                                                                      
#   [9] "INSA Rouen Normandie"                                                                          
#  [10] "ISEN Lille"                                                                                    
#  [11] "CPE Lyon"                                                                                      
#  [12] "ISEP Paris"                                                                                    
#  [13] "ESEO Paris - Vélizy"                                                                           
#  [14] "ESIEE Paris"                                                                                   
#  [15] "ESTACA Laval"                                                                                  
#  [16] "EIGSI La Rochelle"                                                                             
#  [17] "EPF Sceaux"                                                                                    
#  [18] "IPSA Paris"                                                                                    
#  [19] "EPITA Paris"                                                                                   
#  [20] "ESME Sudria Paris"                                                                             
#  [21] "3iL"                                                                                           
#  [22] "IUT Aix-Marseille - Site de Marseille Luminy"                                                  
#  [23] "I.U.T. Nantes"                                                                                 
#  [24] "UTBM Université de Technologie de Belfort Montbéliard"                                         
#  [25] "I.U.T. de Clermont-Ferrand"                                                                    
#  [26] "ESIROI La Réunion"                                                                             
#  [27] "ESIROI La Réunion"                                                                             
#  [28] "I.U.T de Blois"                                                                                
#  [29] "ESIGELEC Rouen"                                                                                
#  [30] "EPITA Lyon"                                                                                    
#  [31] "EPITA Toulouse"                                                                                
#  [32] "ISEN Brest"                                                                                    
#  [33] "ENSAM - campus de Châlons-en-Champagne"                                                        
#  [34] "CPBx (ENSCBP département Chimie Physique)"                                                     
#  [35] "CPBx (ENSCBP département Sciences et Techniques des Aliments)"                                 
#  [36] "CPBx (ENSC)"                                                                                   
#  [37] "CPI Rennes (ENS Chimie Rennes)"                                                                
#  [38] "ISTOM"                                                                                         
#  [39] "AGROCAMPUS OUEST Rennes"                                                                       
#  [40] "Lycée Jean XXIII"                                                                              
#  [41] "Lycée Jean XXIII"                                                                              
#  [42] "ISMANS CESI - Le Mans"                                                                         
#  [43] "ISEN Brest"                                                                                    
#  [44] "ISEN Lille"                                                                                    
#  [45] "ISEP Paris"                                                                                    
#  [46] "HEI Lille"                                                                                     
#  [47] "ESIEE Paris"                                                                                   
#  [48] "ELISA Aerospace Hauts de France"                                                               
#  [49] "EFREI Paris"                                                                                   
#  [50] "HEI Lille"                                                                                     
#  [51] "ESIEA Laval"                                                                                   
#  [52] "3iL"                                                                                           
#  [53] "ESAIP Angers"                                                                                  
#  [54] "HEI Lille"                                                                                     
#  [55] "ISEP Paris"                                                                                    
#  [56] "Polytech Tours"                                                                                
#  [57] "Polytech Grenoble"                                                                             
#  [58] "EEIGM Nancy - Groupe INP"                                                                      
#  [59] "ISAT Nevers"                                                                                   
#  [60] "Polytech Annecy-Chambéry"                                                                      
#  [61] "Polytech Sorbonne"                                                                             
#  [62] "UTBM Université de Technologie de Belfort Montbéliard"                                         
#  [63] "INSA Rennes"                                                                                   
#  [64] "ESEO Dijon"                                                                                    
#  [65] "HEI Lille"                                                                                     
#  [66] "ESCOM Chimie Compiègne"                                                                        
#  [67] "ESIEE Amiens"                                                                                  
#  [68] "ESIEA Laval"                                                                                   
#  [69] "I.U.T. Annecy"                                                                                 
#  [70] "I.U.T. de Lille A"                                                                             
#  [71] "ESGT Le Mans"                                                                                  
#  [72] "IUT Aix-Marseille - Site de Marseille Luminy"                                                  
#  [73] "IUT Aix-Marseille - Site de Marseille Luminy"                                                  
#  [74] "Polytech Angers"                                                                               
#  [75] "I.U.T de Tarbes"                                                                               
#  [76] "IUT 1 GRENOBLE"                                                                                
#  [77] "ENSIBS Lorient"                                                                                
#  [78] "EFREI Paris"                                                                                   
#  [79] "ESME Sudria Bordeaux"                                                                          
#  [80] "ENSAM - campus d'Angers"                                                                       
#  [81] "ENSAM - campus de Bordeaux"                                                                    
#  [82] "CPI Lille (ENSC Lille)"                                                                        
#  [83] "CPBx (ESTIA)"                                                                                  
#  [84] "EPF Montpellier"                                                                               
#  [85] "EPITA Paris"                                                                                   
#  [86] "ISEN Lille"                                                                                    
#  [87] "ESIEE Amiens"                                                                                  
#  [88] "ELISA Aerospace Bordeaux"                                                                      
#  [89] "ISEN Lille"                                                                                    
#  [90] "HEI Lille"                                                                                     
#  [91] "HEI Lille"                                                                                     
#  [92] "ESAIP Aix-en-Provence"                                                                         
#  [93] "ISEN Lille"                                                                                    
#  [94] "HEI Lille"                                                                                     
#  [95] "ESIEE Paris"                                                                                   
#  [96] "ESAIP Aix-en-Provence"                                                                         
#  [97] "ELISA Aerospace Bordeaux"                                                                      
#  [98] "Ecole Supérieure d'Ingénieur des Travaux de la Construction"                                   
#  [99] "ICAM Lille"                                                                                    
# [100] "ICAM Toulouse"                                                                                 
# [101] "ICAM Toulouse"                                                                                 
# [102] "CESI Ecole d'ingénieurs - Bordeaux"                                                            
# [103] "CESI Ecole d'ingénieurs - Lille"                                                               
# [104] "CESI Ecole d'ingénieurs - La Rochelle"                                                         
# [105] "CESI Ecole d'ingénieurs - Rouen"                                                               
# [106] "CESI Ecole d'ingénieurs - Montpellier"                                                         
# [107] "CESI Ecole d'ingénieurs - Nice"                                                                
# [108] "IPSA Paris"                                                                                    
# [109] "ESAIP Aix-en-Provence"                                                                         
# [110] "ISEN Lille"                                                                                    
# [111] "ISEN Lille"                                                                                    
# [112] "Yncréa méditérranée"                                                                           
# [113] "ESA - Ecole Supérieure d'Agricultures"                                                         
# [114] "ISARA"                                                                                         
# [115] "Ecole d'ingénieurs de PURPAN"                                                                  
# [116] "EFREI Paris"                                                                                   
# [117] "EISTI Cergy-Paris"                                                                             
# [118] "ESILV - Paris la Défense"                                                                      
# [119] "ESILV - Paris la Défense"                                                                      
# [120] "Yncréa méditérranée"                                                                           
# [121] "CPI Rennes (ENS Chimie Rennes)"                                                                
# [122] "CY TECH - Université de Cergy-Pontoise"                                                        
# [123] "ECAM Strasbourg-Europe"                                                                        
# [124] "ECAM Strasbourg-Europe"                                                                        
# [125] "UniLaSalle Rouen"                                                                              
# [126] "UniLaSalle Rouen"                                                                              
# [127] "UniLaSalle Beauvais"                                                                           
# [128] "Sup'Biotech Lyon"                                                                              
# [129] "HEI Lille"                                                                                     
# [130] "ISEN Lille"                                                                                    
# [131] "I.U.T. La Roche-sur-Yon"                                                                       
# [132] "ICAM Lille"                                                                                    
# [133] "ICAM Nantes"                                                                                   
# [134] "ICAM Vendée"                                                                                   
# [135] "CESI Ecole d'ingénieurs - Arras"                                                               
# [136] "CESI Ecole d'ingénieurs - Le Mans"                                                             
# [137] "CESI Ecole d'ingénieurs - Orléans"                                                             
# [138] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [139] "ISEN Lille"                                                                                    
# [140] "EFREI Paris"                                                                                   
# [141] "Yncréa méditérranée"                                                                           
# [142] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [143] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [144] "ENSIBS Lorient"                                                                                
# [145] "ESA - Ecole Supérieure d'Agricultures"                                                         
# [146] "Ecole d'ingénieurs de PURPAN"                                                                  
# [147] "ESA - Ecole Supérieure d'Agricultures"                                                         
# [148] "ISARA"                                                                                         
# [149] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [150] "ESILV - Paris la Défense"                                                                      
# [151] "CY TECH - Université de Cergy-Pontoise"                                                        
# [152] "ECAM Lyon"                                                                                     
# [153] "UniLaSalle Rennes"                                                                             
# [154] "ECAM EPMI"                                                                                     
# [155] "UniLaSalle Rennes"                                                                             
# [156] "Ecole d'ingénieurs privée ECAM EPMI"                                                           
# [157] "UniLaSalle Rouen"                                                                              
# [158] "UniLaSalle Rennes"                                                                             
# [159] "ECAM EPMI"                                                                                     
# [160] "Sup'Biotech Lyon"                                                                              
# [161] "ESIEA Laval"                                                                                   
# [162] "ESIEA Paris"                                                                                   
# [163] "AGROCAMPUS OUEST Rennes"                                                                       
# [164] "ICAM Lille"                                                                                    
# [165] "ICAM Paris Sénart"                                                                             
# [166] "ICAM Paris Sénart"                                                                             
# [167] "ICAM Paris Sénart"                                                                             
# [168] "CESI Ecole d'ingénieurs - Pau"                                                                 
# [169] "CESI Ecole d'ingénieurs - Nancy"                                                               
# [170] "ISEN Lille"                                                                                    
# [171] "ISEN Lille"                                                                                    
# [172] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [173] "Ecole d'ingénieurs de PURPAN"                                                                  
# [174] "ISARA"                                                                                         
# [175] "Lycée Baimbridge"                                                                              
# [176] "EPF Sceaux"                                                                                    
# [177] "INSA Rennes"                                                                                   
# [178] "INSA Toulouse"                                                                                 
# [179] "ECAM Lyon"                                                                                     
# [180] "ECAM EPMI"                                                                                     
# [181] "Lycée La Salle Passy Buzenval"                                                                 
# [182] "UniLaSalle Beauvais"                                                                           
# [183] "La Prépa des INP - Groupe INP - Grenoble"                                                      
# [184] "ESIREM Dijon"                                                                                  
# [185] "Polytech Montpellier"                                                                          
# [186] "IMT Lille Douai"                                                                               
# [187] "Polytech Clermont-Ferrand"                                                                     
# [188] "ISEL Le Havre"                                                                                 
# [189] "ISTY Mantes-Vélizy"                                                                            
# [190] "Polytech Paris-Saclay"                                                                         
# [191] "ENIM Metz"                                                                                     
# [192] "UTT Université de Technologie de Troyes"                                                       
# [193] "INSA Toulouse"                                                                                 
# [194] "INSA Lyon"                                                                                     
# [195] "ENSIL-ENSCI - Partenaire INSA"                                                                 
# [196] "ISEN Lille"                                                                                    
# [197] "CPE Lyon"                                                                                      
# [198] "EIGSI La Rochelle"                                                                             
# [199] "ECE Paris"                                                                                     
# [200] "EPF Sceaux"                                                                                    
# [201] "ENSIM Le Mans"                                                                                 
# [202] "IPSA Toulouse"                                                                                 
# [203] "EFREI Paris"                                                                                   
# [204] "EBI"                                                                                           
# [205] "ESIEA Paris"                                                                                   
# [206] "Institut Universitaire de Technologie de TOURS"                                                
# [207] "CPI Pau (ENSGTI)"                                                                              
# [208] "ESAIP Angers"                                                                                  
# [209] "INSA Euro-Méditerranée"                                                                        
# [210] "EFREI Paris"                                                                                   
# [211] "ESIGELEC Rouen"                                                                                
# [212] "ISEN Nantes"                                                                                   
# [213] "EIGSI Casablanca (Maroc)"                                                                      
# [214] "IG2I"                                                                                          
# [215] "EISTI Pau"                                                                                     
# [216] "CPI Strasbourg (ECPM)"                                                                         
# [217] "EPF Montpellier"                                                                               
# [218] "Lycée Jean XXIII"                                                                              
# [219] "Sup'Biotech Paris"                                                                             
# [220] "ESITC Caen"                                                                                    
# [221] "ELISA Aerospace Bordeaux"                                                                      
# [222] "ESAIP Angers"                                                                                  
# [223] "ISEN Lille"                                                                                    
# [224] "ESEO Angers"                                                                                   
# [225] "CPE Lyon"                                                                                      
# [226] "CPE Lyon"                                                                                      
# [227] "Yncréa méditérranée"                                                                           
# [228] "ESIEA Paris"                                                                                   
# [229] "3iL"                                                                                           
# [230] "HEI Lille"                                                                                     
# [231] "ISEP Paris"                                                                                    
# [232] "ESAIP Angers"                                                                                  
# [233] "ESIEA Paris"                                                                                   
# [234] "ELISA Aerospace Hauts de France"                                                               
# [235] "HEI Lille"                                                                                     
# [236] "ISEN Lille"                                                                                    
# [237] "EFREI Paris"                                                                                   
# [238] "AgroSup Dijon"                                                                                 
# [239] "ICAM Bretagne"                                                                                 
# [240] "CESI Ecole d'ingénieurs - Labège"                                                              
# [241] "CESI Ecole d'Ingénieurs - Strasbourg"                                                          
# [242] "CESI Ecole d'ingénieurs - Saint Nazaire"                                                       
# [243] "ESME Sudria Paris"                                                                             
# [244] "ESAIP Angers"                                                                                  
# [245] "Yncréa méditérranée"                                                                           
# [246] "ENSIBS Vannes"                                                                                 
# [247] "ISA"                                                                                           
# [248] "ISA"                                                                                           
# [249] "ISEP Paris"                                                                                    
# [250] "ECE Paris"                                                                                     
# [251] "EPF Montpellier"                                                                               
# [252] "ESAIP Angers"                                                                                  
# [253] "CY TECH - Université de Cergy-Pontoise"                                                        
# [254] "ECAM Lyon"                                                                                     
# [255] "ECAM Strasbourg-Europe"                                                                        
# [256] "UniLaSalle Rouen"                                                                              
# [257] "UniLaSalle Rouen"                                                                              
# [258] "La Prépa des INP - Groupe INP - Bordeaux"                                                      
# [259] "La Prépa des INP - Groupe INP - Saint-Denis de la Réunion"                                     
# [260] "Polytech Nice Sophia"                                                                          
# [261] "Télécom Saint-Etienne"                                                                         
# [262] "Polytech Nantes"                                                                               
# [263] "Sup Galilée Paris"                                                                             
# [264] "INSA Toulouse"                                                                                 
# [265] "ISEN Rennes"                                                                                   
# [266] "EPF Troyes"                                                                                    
# [267] "ESTACA Laval"                                                                                  
# [268] "ESME Sudria Paris"                                                                             
# [269] "EPITA Paris"                                                                                   
# [270] "La Prépa des INP - Groupe INP - Valence"                                                       
# [271] "I.U.T. Angers-Cholet - Site d'Angers"                                                          
# [272] "I.U.T d'Allier (Montluçon, Moulins, Vichy)"                                                    
# [273] "IUT 1 GRENOBLE"                                                                                
# [274] "Grenoble INP - ESISAR Valence"                                                                 
# [275] "I.U.T. Annecy"                                                                                 
# [276] "I.U.T d'Allier (Montluçon, Moulins, Vichy)"                                                    
# [277] "I.U.T. de Clermont-Ferrand"                                                                    
# [278] "IUT Aix-Marseille - Site de Marseille Luminy"                                                  
# [279] "ELISA Aerospace Hauts de France"                                                               
# [280] "ENSCMu - partenaire INSA"                                                                      
# [281] "ENSISA - partenaire INSA"                                                                      
# [282] "ESIEA Paris"                                                                                   
# [283] "Sup'Biotech Paris"                                                                             
# [284] "EPITA Rennes"                                                                                  
# [285] "EPITA Strasbourg"                                                                              
# [286] "SUP ENR - partenaire INSA"                                                                     
# [287] "ESAIP Aix-en-Provence"                                                                         
# [288] "ECE Lyon"                                                                                      
# [289] "CPBx (ENSEIRB-MATMECA)"                                                                        
# [290] "CPBx (Bordeaux Sciences Agro.)"                                                                
# [291] "Iteem"                                                                                         
# [292] "EIL Côte d'Opale"                                                                              
# [293] "CPI Clermont-Ferrand (Sigma Clermont)"                                                         
# [294] "CPBx (ENSGTI)"                                                                                 
# [295] "ISA BTP"                                                                                       
# [296] "INP-ENIT Tarbes"                                                                               
# [297] "ISEL Le Havre"                                                                                 
# [298] "EISTI Cergy-Paris"                                                                             
# [299] "CPBx (ENSEGID)"                                                                                
# [300] "ESILV - Paris la Défense"                                                                      
# [301] "ESILV - Paris la Défense"                                                                      
# [302] "ESME Sudria Lyon"                                                                              
# [303] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [304] "HEI Lille"                                                                                     
# [305] "ISEN Lille"                                                                                    
# [306] "ESCOM Chimie Compiègne"                                                                        
# [307] "ISEP Paris"                                                                                    
# [308] "ESEO Paris - Vélizy"                                                                           
# [309] "EFREI Paris"                                                                                   
# [310] "ESIEA Laval"                                                                                   
# [311] "ESAIP Angers"                                                                                  
# [312] "ESAIP Aix-en-Provence"                                                                         
# [313] "ESIEA Paris"                                                                                   
# [314] "3iL"                                                                                           
# [315] "HEI Lille"                                                                                     
# [316] "ESEO Angers"                                                                                   
# [317] "ESIEA Paris"                                                                                   
# [318] "ESIEE Amiens"                                                                                  
# [319] "ISEN Lille"                                                                                    
# [320] "ISEN Lille"                                                                                    
# [321] "UniLaSalle Rennes"                                                                             
# [322] "ESEO Angers"                                                                                   
# [323] "Université Jean Monnet - Campus de Roanne"                                                     
# [324] "ENISE Saint-Etienne"                                                                           
# [325] "ICAM Nantes"                                                                                   
# [326] "ICAM Toulouse"                                                                                 
# [327] "CESI Ecole d'ingénieurs - Aix-En-Provence"                                                     
# [328] "CESI Ecole d'ingénieurs - Brest"                                                               
# [329] "CESI Ecole d'ingénieurs - Caen"                                                                
# [330] "CESI Ecole d'ingénieurs - Ecully"                                                              
# [331] "CESI Ecole d'ingénieurs - La Couronne - Angoulême"                                             
# [332] "CESI Ecole d'ingénieurs - Nanterre"                                                            
# [333] "CESI Ecole d'ingénieurs - Reims"                                                               
# [334] "Sup'Biotech Paris"                                                                             
# [335] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
# [336] "ISA"                                                                                           
# [337] "EFREI Paris"                                                                                   
# [338] "CESI Ecole d'ingénieurs - Dijon"                                                               
# [339] "CPBx (ENSPIMA)"                                                                                
# [340] "EPF Sceaux"                                                                                    
# [341] "Cursus Humanités et technologie UTC Université de Technologie de Compiègne"                    
# [342] "CY TECH - Université de Cergy-Pontoise"                                                        
# [343] "ISEN Yncrea Ouest Caen"                                                                        
# [344] "ISEN Yncrea Ouest Caen"                                                                        
# [345] "ISEN Yncrea Ouest Caen"                                                                        
# [346] "ECAM Rennes"                                                                                   
# [347] "Ecole d'ingénieurs privée ECAM EPMI"                                                           
# [348] "UniLaSalle Beauvais"                                                                           
# [349] "Ecole d'ingénieurs privée ECAM EPMI"                                                           
# [350] "UniLaSalle Rouen"                                                                              
# [351] "Lycée St J-B De La Salle"                                                                      
# [352] "La Prépa des INP - Groupe INP - Nancy"                                                         
# [353] "Polytech Marseille"                                                                            
# [354] "AgroSup Dijon"                                                                                 
# [355] "Polytech Montpellier"                                                                          
# [356] "Polytech Angers"                                                                               
# [357] "Polytech Nancy"                                                                                
# [358] "ENSGSI Nancy - Groupe INP"                                                                     
# [359] "Polytech Lyon"                                                                                 
# [360] "Polytech Sorbonne"                                                                             
# [361] "ENIB Brest"                                                                                    
# [362] "UTC Université de Technologie de Compiègne"                                                    
# [363] "INSA Strasbourg"                                                                               
# [364] "INSA Lyon"                                                                                     
# [365] "ISEN Brest"                                                                                    
# [366] "ISEN Brest"                                                                                    
# [367] "ESEO Angers"                                                                                   
# [368] "Yncréa méditérranée"                                                                           
# [369] "ECE Paris"                                                                                     
# [370] "EPF Sceaux"                                                                                    
# [371] "ESTACA Paris-Saclay (Saint-Quentin-en-Yvelines)"                                               
# [372] "ESME Sudria Lyon"                                                                              
# [373] "ESME Sudria Lille"                                                                             
# [374] "I.U.T. Le Mans"                                                                                
# [375] "I.U.T d'Orléans"                                                                               
# [376] "Cursus Humanités et technologie UTC Université de Technologie de Compiègne"                    
# [377] "ISIS - Partenaire INSA"                                                                        
# [378] "INSA Hauts-de-France"                                                                          
# [379] "I.U.T. Le Mans"                                                                                
# [380] "I.U.T d'Orléans"                                                                               
# [381] "IUT Aix-Marseille - Site de Marseille Luminy"                                                  
# [382] "I.U.T. Nantes"                                                                                 
# [383] "ISEN Nantes"                                                                                   
# [384] "ISEN Brest"                                                                                    
# [385] "ESITECH - partenaire INSA"                                                                     
# [386] "CPBx (ENSTBB)"                                                                                 
# [387] "UniLaSalle Beauvais"                                                                           
# [388] "ESITC Paris"                                                                                   
# [389] "AGROCAMPUS OUEST Angers"                                                                       
# [390] "ISEL Le Havre"                                                                                 
# [391] "ESITC Caen"                                                                                    
# [392] "HEI Lille"                                                                                     
# [393] "ESEO Dijon"                                                                                    
# [394] "ISEN Lille"                                                                                    
# [395] "ESEO Angers"                                                                                   
# [396] "EFREI Paris"                                                                                   
# [397] "ESCOM Chimie Compiègne"                                                                        
# [398] "EBI"                                                                                           
# [399] "ESEO Angers"                                                                                   
# [400] "ISEN Lille"                                                                                    
# [401] "EFREI Paris"                                                                                   
# [402] "ESIEA Laval"                                                                                   
# > Ecoles_inge=Table_ecoles_ingenieurs$Établissement 
# > unique(Ecoles_inge)  
#   [1] "La Prépa des INP - Groupe INP - Toulouse"                                                      
#   [2] "Polytech Orléans"                                                                              
#   [3] "Polytech Lille"                                                                                
#   [4] "Polytech Clermont-Ferrand"                                                                     
#   [5] "ENIB Brest"                                                                                    
#   [6] "ENIM Metz"                                                                                     
#   [7] "INSA Centre Val de Loire"                                                                      
#   [8] "INSA Rouen Normandie"                                                                          
#   [9] "ISEN Lille"                                                                                    
#  [10] "CPE Lyon"                                                                                      
#  [11] "ISEP Paris"                                                                                    
#  [12] "ESEO Paris - Vélizy"                                                                           
#  [13] "ESIEE Paris"                                                                                   
#  [14] "ESTACA Laval"                                                                                  
#  [15] "EIGSI La Rochelle"                                                                             
#  [16] "EPF Sceaux"                                                                                    
#  [17] "IPSA Paris"                                                                                    
#  [18] "EPITA Paris"                                                                                   
#  [19] "ESME Sudria Paris"                                                                             
#  [20] "3iL"                                                                                           
#  [21] "IUT Aix-Marseille - Site de Marseille Luminy"                                                  
#  [22] "I.U.T. Nantes"                                                                                 
#  [23] "UTBM Université de Technologie de Belfort Montbéliard"                                         
#  [24] "I.U.T. de Clermont-Ferrand"                                                                    
#  [25] "ESIROI La Réunion"                                                                             
#  [26] "I.U.T de Blois"                                                                                
#  [27] "ESIGELEC Rouen"                                                                                
#  [28] "EPITA Lyon"                                                                                    
#  [29] "EPITA Toulouse"                                                                                
#  [30] "ISEN Brest"                                                                                    
#  [31] "ENSAM - campus de Châlons-en-Champagne"                                                        
#  [32] "CPBx (ENSCBP département Chimie Physique)"                                                     
#  [33] "CPBx (ENSCBP département Sciences et Techniques des Aliments)"                                 
#  [34] "CPBx (ENSC)"                                                                                   
#  [35] "CPI Rennes (ENS Chimie Rennes)"                                                                
#  [36] "ISTOM"                                                                                         
#  [37] "AGROCAMPUS OUEST Rennes"                                                                       
#  [38] "Lycée Jean XXIII"                                                                              
#  [39] "ISMANS CESI - Le Mans"                                                                         
#  [40] "HEI Lille"                                                                                     
#  [41] "ELISA Aerospace Hauts de France"                                                               
#  [42] "EFREI Paris"                                                                                   
#  [43] "ESIEA Laval"                                                                                   
#  [44] "ESAIP Angers"                                                                                  
#  [45] "Polytech Tours"                                                                                
#  [46] "Polytech Grenoble"                                                                             
#  [47] "EEIGM Nancy - Groupe INP"                                                                      
#  [48] "ISAT Nevers"                                                                                   
#  [49] "Polytech Annecy-Chambéry"                                                                      
#  [50] "Polytech Sorbonne"                                                                             
#  [51] "INSA Rennes"                                                                                   
#  [52] "ESEO Dijon"                                                                                    
#  [53] "ESCOM Chimie Compiègne"                                                                        
#  [54] "ESIEE Amiens"                                                                                  
#  [55] "I.U.T. Annecy"                                                                                 
#  [56] "I.U.T. de Lille A"                                                                             
#  [57] "ESGT Le Mans"                                                                                  
#  [58] "Polytech Angers"                                                                               
#  [59] "I.U.T de Tarbes"                                                                               
#  [60] "IUT 1 GRENOBLE"                                                                                
#  [61] "ENSIBS Lorient"                                                                                
#  [62] "ESME Sudria Bordeaux"                                                                          
#  [63] "ENSAM - campus d'Angers"                                                                       
#  [64] "ENSAM - campus de Bordeaux"                                                                    
#  [65] "CPI Lille (ENSC Lille)"                                                                        
#  [66] "CPBx (ESTIA)"                                                                                  
#  [67] "EPF Montpellier"                                                                               
#  [68] "ELISA Aerospace Bordeaux"                                                                      
#  [69] "ESAIP Aix-en-Provence"                                                                         
#  [70] "Ecole Supérieure d'Ingénieur des Travaux de la Construction"                                   
#  [71] "ICAM Lille"                                                                                    
#  [72] "ICAM Toulouse"                                                                                 
#  [73] "CESI Ecole d'ingénieurs - Bordeaux"                                                            
#  [74] "CESI Ecole d'ingénieurs - Lille"                                                               
#  [75] "CESI Ecole d'ingénieurs - La Rochelle"                                                         
#  [76] "CESI Ecole d'ingénieurs - Rouen"                                                               
#  [77] "CESI Ecole d'ingénieurs - Montpellier"                                                         
#  [78] "CESI Ecole d'ingénieurs - Nice"                                                                
#  [79] "Yncréa méditérranée"                                                                           
#  [80] "ESA - Ecole Supérieure d'Agricultures"                                                         
#  [81] "ISARA"                                                                                         
#  [82] "Ecole d'ingénieurs de PURPAN"                                                                  
#  [83] "EISTI Cergy-Paris"                                                                             
#  [84] "ESILV - Paris la Défense"                                                                      
#  [85] "CY TECH - Université de Cergy-Pontoise"                                                        
#  [86] "ECAM Strasbourg-Europe"                                                                        
#  [87] "UniLaSalle Rouen"                                                                              
#  [88] "UniLaSalle Beauvais"                                                                           
#  [89] "Sup'Biotech Lyon"                                                                              
#  [90] "I.U.T. La Roche-sur-Yon"                                                                       
#  [91] "ICAM Nantes"                                                                                   
#  [92] "ICAM Vendée"                                                                                   
#  [93] "CESI Ecole d'ingénieurs - Arras"                                                               
#  [94] "CESI Ecole d'ingénieurs - Le Mans"                                                             
#  [95] "CESI Ecole d'ingénieurs - Orléans"                                                             
#  [96] "ISEN Méditerranée (Campus Nîmes) CPGE associée YNCREA (ISEN-HEI-ISA) Saint Joseph Pierre Rouge"
#  [97] "ECAM Lyon"                                                                                     
#  [98] "UniLaSalle Rennes"                                                                             
#  [99] "ECAM EPMI"                                                                                     
# [100] "Ecole d'ingénieurs privée ECAM EPMI"                                                           
# [101] "ESIEA Paris"                                                                                   
# [102] "ICAM Paris Sénart"                                                                             
# [103] "CESI Ecole d'ingénieurs - Pau"                                                                 
# [104] "CESI Ecole d'ingénieurs - Nancy"                                                               
# [105] "Lycée Baimbridge"                                                                              
# [106] "INSA Toulouse"                                                                                 
# [107] "Lycée La Salle Passy Buzenval"                                                                 
# [108] "La Prépa des INP - Groupe INP - Grenoble"                                                      
# [109] "ESIREM Dijon"                                                                                  
# [110] "Polytech Montpellier"                                                                          
# [111] "IMT Lille Douai"                                                                               
# [112] "ISEL Le Havre"                                                                                 
# [113] "ISTY Mantes-Vélizy"                                                                            
# [114] "Polytech Paris-Saclay"                                                                         
# [115] "UTT Université de Technologie de Troyes"                                                       
# [116] "INSA Lyon"                                                                                     
# [117] "ENSIL-ENSCI - Partenaire INSA"                                                                 
# [118] "ECE Paris"                                                                                     
# [119] "ENSIM Le Mans"                                                                                 
# [120] "IPSA Toulouse"                                                                                 
# [121] "EBI"                                                                                           
# [122] "Institut Universitaire de Technologie de TOURS"                                                
# [123] "CPI Pau (ENSGTI)"                                                                              
# [124] "INSA Euro-Méditerranée"                                                                        
# [125] "ISEN Nantes"                                                                                   
# [126] "EIGSI Casablanca (Maroc)"                                                                      
# [127] "IG2I"                                                                                          
# [128] "EISTI Pau"                                                                                     
# [129] "CPI Strasbourg (ECPM)"                                                                         
# [130] "Sup'Biotech Paris"                                                                             
# [131] "ESITC Caen"                                                                                    
# [132] "ESEO Angers"                                                                                   
# [133] "AgroSup Dijon"                                                                                 
# [134] "ICAM Bretagne"                                                                                 
# [135] "CESI Ecole d'ingénieurs - Labège"                                                              
# [136] "CESI Ecole d'Ingénieurs - Strasbourg"                                                          
# [137] "CESI Ecole d'ingénieurs - Saint Nazaire"                                                       
# [138] "ENSIBS Vannes"                                                                                 
# [139] "ISA"                                                                                           
# [140] "La Prépa des INP - Groupe INP - Bordeaux"                                                      
# [141] "La Prépa des INP - Groupe INP - Saint-Denis de la Réunion"                                     
# [142] "Polytech Nice Sophia"                                                                          
# [143] "Télécom Saint-Etienne"                                                                         
# [144] "Polytech Nantes"                                                                               
# [145] "Sup Galilée Paris"                                                                             
# [146] "ISEN Rennes"                                                                                   
# [147] "EPF Troyes"                                                                                    
# [148] "La Prépa des INP - Groupe INP - Valence"                                                       
# [149] "I.U.T. Angers-Cholet - Site d'Angers"                                                          
# [150] "I.U.T d'Allier (Montluçon, Moulins, Vichy)"                                                    
# [151] "Grenoble INP - ESISAR Valence"                                                                 
# [152] "ENSCMu - partenaire INSA"                                                                      
# [153] "ENSISA - partenaire INSA"                                                                      
# [154] "EPITA Rennes"                                                                                  
# [155] "EPITA Strasbourg"                                                                              
# [156] "SUP ENR - partenaire INSA"                                                                     
# [157] "ECE Lyon"                                                                                      
# [158] "CPBx (ENSEIRB-MATMECA)"                                                                        
# [159] "CPBx (Bordeaux Sciences Agro.)"                                                                
# [160] "Iteem"                                                                                         
# [161] "EIL Côte d'Opale"                                                                              
# [162] "CPI Clermont-Ferrand (Sigma Clermont)"                                                         
# [163] "CPBx (ENSGTI)"                                                                                 
# [164] "ISA BTP"                                                                                       
# [165] "INP-ENIT Tarbes"                                                                               
# [166] "CPBx (ENSEGID)"                                                                                
# [167] "ESME Sudria Lyon"                                                                              
# [168] "Université Jean Monnet - Campus de Roanne"                                                     
# [169] "ENISE Saint-Etienne"                                                                           
# [170] "CESI Ecole d'ingénieurs - Aix-En-Provence"                                                     
# [171] "CESI Ecole d'ingénieurs - Brest"                                                               
# [172] "CESI Ecole d'ingénieurs - Caen"                                                                
# [173] "CESI Ecole d'ingénieurs - Ecully"                                                              
# [174] "CESI Ecole d'ingénieurs - La Couronne - Angoulême"                                             
# [175] "CESI Ecole d'ingénieurs - Nanterre"                                                            
# [176] "CESI Ecole d'ingénieurs - Reims"                                                               
# [177] "CESI Ecole d'ingénieurs - Dijon"                                                               
# [178] "CPBx (ENSPIMA)"                                                                                
# [179] "Cursus Humanités et technologie UTC Université de Technologie de Compiègne"                    
# [180] "ISEN Yncrea Ouest Caen"                                                                        
# [181] "ECAM Rennes"                                                                                   
# [182] "Lycée St J-B De La Salle"                                                                      
# [183] "La Prépa des INP - Groupe INP - Nancy"                                                         
# [184] "Polytech Marseille"                                                                            
# [185] "Polytech Nancy"                                                                                
# [186] "ENSGSI Nancy - Groupe INP"                                                                     
# [187] "Polytech Lyon"                                                                                 
# [188] "UTC Université de Technologie de Compiègne"                                                    
# [189] "INSA Strasbourg"                                                                               
# [190] "ESTACA Paris-Saclay (Saint-Quentin-en-Yvelines)"                                               
# [191] "ESME Sudria Lille"                                                                             
# [192] "I.U.T. Le Mans"                                                                                
# [193] "I.U.T d'Orléans"                                                                               
# [194] "ISIS - Partenaire INSA"                                                                        
# [195] "INSA Hauts-de-France"                                                                          
# [196] "ESITECH - partenaire INSA"                                                                     
# [197] "CPBx (ENSTBB)"                                                                                 
# [198] "ESITC Paris"                                                                                   
# [199] "AGROCAMPUS OUEST Angers"        